
    /* Try to think of a factor that could make sense for this prediction. How could it be infer / predicted based on the input parameter available to the function, implement it in the function. here is a sample input for reference, so you can look at available parameters:
Id="1311", MSSubClass="20", MSZoning="RL", LotFrontage="100", LotArea="17500", Street="Pave", Alley="NA", LotShape="Reg", LandContour="Lvl", Utilities="AllPub", LotConfig="Inside", LandSlope="Gtl", Neighborhood="Crawfor", Condition1="PosA", Condition2="Norm", BldgType="1Fam", HouseStyle="1Story", OverallQual="7", OverallCond="8", YearBuilt="1959", YearRemodAdd="2002", RoofStyle="Gable", RoofMatl="CompShg", Exterior1st="BrkFace", Exterior2nd="HdBoard", MasVnrType="None", MasVnrArea="0", ExterQual="Gd", ExterCond="Gd", Foundation="PConc", BsmtQual="Gd", BsmtCond="TA", BsmtExposure="Av", BsmtFinType1="GLQ", BsmtFinSF1="1406", BsmtFinType2="Unf", BsmtFinSF2="0", BsmtUnfSF="496", TotalBsmtSF="1902", Heating="GasA", HeatingQC="TA", CentralAir="Y", Electrical="SBrkr", _1stFlrSF=undefined, _2ndFlrSF=undefined, LowQualFinSF="0", GrLivArea="1902", BsmtFullBath="1", BsmtHalfBath="0", FullBath="2", HalfBath="0", BedroomAbvGr="3", KitchenAbvGr="1", KitchenQual="Ex", TotRmsAbvGrd="7", Functional="Typ", Fireplaces="2", FireplaceQu="TA", GarageType="Attchd", GarageYrBlt="1959", GarageFinish="Fin", GarageCars="2", GarageArea="567", GarageQual="TA", GarageCond="TA", PavedDrive="Y", WoodDeckSF="0", OpenPorchSF="207", EnclosedPorch="162", _3SsnPorch=undefined, ScreenPorch="0", PoolArea="0", PoolQC="NA", Fence="NA", MiscFeature="NA", MiscVal="0", MoSold="5", YrSold="2010", SaleType="WD", SaleCondition="Normal" */
    
    
function predictHousePrice(OverallQual, YearBuilt, TotalBsmtSF, GrLivArea, FullBath, GarageCars, GarageArea) {
  var predictedPrice = 5000 * OverallQual + 2000 * YearBuilt + 100 * TotalBsmtSF + 300 * GrLivArea + 10000 * FullBath + 5000 * GarageCars + 100 * GarageArea;
  return predictedPrice;
}
