
    /* Try to think of a factor that could make sense for this prediction. How could it be infer / predicted based on the input parameter available to the function, implement it in the function. here is a sample input for reference, so you can look at available parameters:
Id="Id=\"291\"", MSSubClass="MSSubClass=\"60\"", MSZoning="MSZoning=\"RL\"", LotFrontage="LotFrontage=\"120\"", LotArea="LotArea=\"15611\"", Street="Street=\"Pave\"", Alley="Alley=\"NA\"", LotShape="LotShape=\"Reg\"", LandContour="LandContour=\"Lvl\"", Utilities="Utilities=\"AllPub\"", LotConfig="LotConfig=\"Inside\"", LandSlope="LandSlope=\"Gtl\"", Neighborhood="Neighborhood=\"CollgCr\"", Condition1="Condition1=\"Norm\"", Condition2="Condition2=\"Norm\"", BldgType="BldgType=\"1Fam\"", HouseStyle="HouseStyle=\"2Story\"", OverallQual="OverallQual=\"8\"", OverallCond="OverallCond=\"5\"", YearBuilt="YearBuilt=\"2006\"", YearRemodAdd="YearRemodAdd=\"2006\"", RoofStyle="RoofStyle=\"Gable\"", RoofMatl="RoofMatl=\"CompShg\"", Exterior1st="Exterior1st=\"VinylSd\"", Exterior2nd="Exterior2nd=\"VinylSd\"", MasVnrType="MasVnrType=\"None\"", MasVnrArea="MasVnrArea=\"0\"", ExterQual="ExterQual=\"Gd\"", ExterCond="ExterCond=\"TA\"", Foundation="Foundation=\"PConc\"", BsmtQual="BsmtQual=\"Gd\"", BsmtCond="BsmtCond=\"TA\"", BsmtExposure="BsmtExposure=\"Av\"", BsmtFinType1="BsmtFinType1=\"Unf\"", BsmtFinSF1="BsmtFinSF1=\"0\"", BsmtFinType2="BsmtFinType2=\"Unf\"", BsmtFinSF2="BsmtFinSF2=\"0\"", BsmtUnfSF="BsmtUnfSF=\"1079\"", TotalBsmtSF="TotalBsmtSF=\"1079\"", Heating="Heating=\"GasA\"", HeatingQC="HeatingQC=\"Ex\"", CentralAir="CentralAir=\"Y\"", Electrical="Electrical=\"SBrkr\"", _1stFlrSF="_1stFlrSF=undefined", _2ndFlrSF="_2ndFlrSF=undefined", LowQualFinSF="LowQualFinSF=\"0\"", GrLivArea="GrLivArea=\"1919\"", BsmtFullBath="BsmtFullBath=\"0\"", BsmtHalfBath="BsmtHalfBath=\"0\"", FullBath="FullBath=\"2\"", HalfBath="HalfBath=\"1\"", BedroomAbvGr="BedroomAbvGr=\"3\"", KitchenAbvGr="KitchenAbvGr=\"1\"", KitchenQual="KitchenQual=\"Gd\"", TotRmsAbvGrd="TotRmsAbvGrd=\"8\"", Functional="Functional=\"Typ\"", Fireplaces="Fireplaces=\"1\"", FireplaceQu="FireplaceQu=\"Gd\"", GarageType="GarageType=\"Attchd\"", GarageYrBlt="GarageYrBlt=\"2006\"", GarageFinish="GarageFinish=\"RFn\"", GarageCars="GarageCars=\"2\"", GarageArea="GarageArea=\"685\"", GarageQual="GarageQual=\"Gd\"", GarageCond="GarageCond=\"TA\"", PavedDrive="PavedDrive=\"Y\"", WoodDeckSF="WoodDeckSF=\"0\"", OpenPorchSF="OpenPorchSF=\"51\"", EnclosedPorch="EnclosedPorch=\"0\"", _3SsnPorch="_3SsnPorch=undefined", ScreenPorch="ScreenPorch=\"0\"", PoolArea="PoolArea=\"0\"", PoolQC="PoolQC=\"NA\"", Fence="Fence=\"NA\"", MiscFeature="MiscFeature=\"NA\"", MiscVal="MiscVal=\"0\"", MoSold="MoSold=\"7\"", YrSold="YrSold=\"2006\"", SaleType="SaleType=\"New\"", SaleCondition="SaleCondition=\"Partial\"" */
    
    
function predictHousePrice(Id, MSSubClass, MSZoning, LotFrontage, LotArea, Street, Alley, LotShape, LandContour, Utilities, LotConfig, LandSlope, Neighborhood, Condition1, Condition2, BldgType, HouseStyle, OverallQual, OverallCond, YearBuilt, YearRemodAdd, RoofStyle, RoofMatl, Exterior1st, Exterior2nd, MasVnrType, MasVnrArea, ExterQual, ExterCond, Foundation, BsmtQual, BsmtCond, BsmtExposure, BsmtFinType1, BsmtFinSF1, BsmtFinType2, BsmtFinSF2, BsmtUnfSF, TotalBsmtSF, Heating, HeatingQC, CentralAir, Electrical, _1stFlrSF, _2ndFlrSF, LowQualFinSF, GrLivArea, BsmtFullBath,
BsmtHalfBath, FullBath, HalfBath, BedroomAbvGr, KitchenAbvGr, KitchenQual, TotRmsAbvGrd, Functional, Fireplaces, FireplaceQu, GarageType, GarageYrBlt, GarageFinish, GarageCars, GarageArea, GarageQual, GarageCond, PavedDrive, WoodDeckSF, OpenPorchSF, EnclosedPorch, _3SsnPorch, ScreenPorch, PoolArea, PoolQC, Fence, MiscFeature, MiscVal, MoSold, YrSold, SaleType, SaleCondition) {
    let predictedPrice = 180000 + (OverallQual * 10000) + (GrLivArea * 50) + (GarageArea * 30) + (TotalBsmtSF * 20) + (YearBuilt * 100) - (MoSold * 1000);
    return predictedPrice;
}
